// <auto-generated />
namespace MVCCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class v2_CreateAllPrice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v2_CreateAllPrice));
        
        string IMigrationMetadata.Id
        {
            get { return "202306032257398_v2_CreateAllPrice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
